import os
import secrets
import string
import psycopg2
import smtplib

from psycopg2.extras import DictCursor
from dotenv import load_dotenv
from functools import wraps
from flask import (
    Flask, render_template, request, redirect,
    url_for, session, flash, jsonify
)
from werkzeug.security import (
    generate_password_hash, check_password_hash
)

load_dotenv()

try:
    from groq import Groq
except ImportError:
    Groq = None


app = Flask(__name__)
app.secret_key = os.environ.get(
    "FLASK_SECRET_KEY",
    "change-this-secret-key-in-production"
)


# PostgreSQL database connection
class DBConnection:
    def __init__(self):
        database_url = os.environ.get("DATABASE_URL")

        if not database_url:
            raise RuntimeError(
                "DATABASE_URL set nahi hai. Render Environment mein "
                "PostgreSQL ka Internal Database URL set karo."
            )

        self.conn = psycopg2.connect(
            database_url,
            cursor_factory=DictCursor
        )

    def cursor(self):
        return self.conn.cursor()

    def execute(self, query, params=None):
        cur = self.conn.cursor()
        cur.execute(query, params)
        return cur

    def executemany(self, query, params):
        cur = self.conn.cursor()
        cur.executemany(query, params)
        return cur

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def close(self):
        self.conn.close()


def db():
    return DBConnection()


# Initialize PostgreSQL tables
def init_db():
    conn = db()

    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'student',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS courses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                description TEXT,
                youtube_url TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        admin = conn.execute(
            "SELECT id FROM users WHERE username = %s",
            ("ritik",)
        ).fetchone()

        if not admin:
            admin_password = os.environ.get("ADMIN_PASSWORD")

            if not admin_password:
                raise RuntimeError(
                    "Render Environment mein ADMIN_PASSWORD set karo."
                )

            conn.execute(
                """INSERT INTO users
                   (username, password_hash, role)
                   VALUES (%s, %s, %s)""",
                (
                    "ritik",
                    generate_password_hash(admin_password),
                    "admin"
                )
            )

        count = conn.execute(
            "SELECT COUNT(*) FROM courses"
        ).fetchone()[0]

        if count == 0:
            conn.executemany(
                """INSERT INTO courses
                   (title, description, youtube_url)
                   VALUES (%s, %s, %s)""",
                [
                    (
                        "Python Basics",
                        "Variables, loops, functions aur beginner Python.",
                        "https://www.youtube.com/watch?v=rfscVS0vtbw"
                    ),
                    (
                        "Python OOP",
                        "Classes, objects aur OOP concepts.",
                        "https://www.youtube.com/watch?v=JeznW_7DlB0"
                    )
                ]
            )

        conn.commit()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))

        return f(*args, **kwargs)

    return wrapper


def admin_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if session.get("role") != "admin":
            flash("Admin access required.", "error")
            return redirect(url_for("dashboard"))

        return f(*args, **kwargs)

    return wrapper


def make_password(length=10):
    alphabet = string.ascii_letters + string.digits + "!@#$"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def youtube_embed(url):
    if not url:
        return ""

    if "youtu.be/" in url:
        video_id = url.split("youtu.be/")[-1].split("?")[0]

    elif "watch?v=" in url:
        video_id = url.split("watch?v=")[-1].split("&")[0]

    elif "youtube.com/embed/" in url:
        video_id = url.split("youtube.com/embed/")[-1].split("?")[0]

    else:
        return ""

    return f"https://www.youtube.com/embed/{video_id}"


@app.context_processor
def inject_helpers():
    return {"youtube_embed": youtube_embed}


@app.route("/")
def index():
    if "user_id" in session:
        return redirect(url_for("dashboard"))

    return render_template("index.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"].strip().lower()
        password = request.form["password"]

        conn = db()

        try:
            user = conn.execute(
                "SELECT * FROM users WHERE username = %s",
                (username,)
            ).fetchone()

        finally:
            conn.close()

        if user and check_password_hash(user["password_hash"], password):
            session["user_id"] = user["id"]
            session["username"] = user["username"]
            session["role"] = user["role"]

            return redirect(url_for("dashboard"))

        flash("Username ya password galat hai.", "error")

    return render_template("login.html")


@app.route("/login/pass", methods=["GET", "POST"])
def passe():
    if request.method == "POST":
        username = request.form["username"].strip().lower()
        oldpassword = request.form["old_password"]
        newpass = request.form["new_password"]
        conpass = request.form["confirm_password"]

        conn = db()

        try:
            user = conn.execute(
                "SELECT * FROM users WHERE username = %s",
                (username,)
            ).fetchone()

            if not user:
                flash("Name galat hai, sahi name daalo...")
                return redirect(url_for("passe"))

            if not check_password_hash(
                user["password_hash"], oldpassword
            ):
                flash("Tumhara purana password galat hai.")
                return redirect(url_for("passe"))

            if newpass != conpass:
                flash("Password aur confirm password match nahi kar rahe.")
                return redirect(url_for("passe"))

            new_password_hash = generate_password_hash(newpass)

            conn.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (new_password_hash, user["id"])
            )

            conn.commit()

            session["user_id"] = user["id"]
            session["username"] = user["username"]
            session["role"] = user["role"]

        finally:
            conn.close()

        return redirect(url_for("dashboard"))

    return render_template("passe.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/dashboard")
@login_required
def dashboard():
    conn = db()

    try:
        courses = conn.execute(
            "SELECT * FROM courses ORDER BY id DESC"
        ).fetchall()

        users_count = conn.execute(
            "SELECT COUNT(*) FROM users"
        ).fetchone()[0]

    finally:
        conn.close()

    return render_template(
        "dashboard.html",
        courses=courses,
        users_count=users_count
    )


@app.route("/admin/users", methods=["GET", "POST"])
@admin_required
def manage_users():
    if request.method == "POST":
        username = request.form["username"].strip().lower()
        gmail = request.form["gmail"]

        print(username)
        print(gmail)

        if not username or " " in username:
            flash("Username valid rakho, spaces nahi.", "error")
            return redirect(url_for("manage_users"))

        def create_password(length=8):
            return "".join(
                secrets.choice(string.ascii_uppercase)
                for _ in range(length)
            )

        temporary_password = create_password()

        print(temporary_password)

        conn = db()

        try:
            conn.execute(
                """INSERT INTO users
                   (username, password_hash, role)
                   VALUES (%s, %s, %s)""",
                (
                    username,
                    generate_password_hash(temporary_password),
                    "student"
                )
            )

            conn.commit()

        except psycopg2.IntegrityError:
            conn.rollback()
            flash("Ye username already exist karta hai.", "error")
            return redirect(url_for("manage_users"))

        finally:
            conn.close()

        try:
            sender = gmail
            apppass = os.environ.get("password_google", "")
            receiver = "Ritiklearnhub@gmail.com"

            message = f"""Subject: Your Password

Your Password Is: {temporary_password}
This is your temporary password.
"""

            with smtplib.SMTP("smtp.gmail.com", 587) as server:
                server.starttls()
                server.login(sender, apppass)
                server.sendmail(sender, receiver, message)

            print("Password is successfully sent")

        except Exception as exc:
            print("Message is not sent:", repr(exc))

        flash(
            f"User {username} create ho gaya. "
            f"Temporary password: {temporary_password} "
            f"gmail= {gmail}",
            "success"
        )

        return redirect(url_for("manage_users"))

    conn = db()

    try:
        users = conn.execute(
            """SELECT id, username, role, created_at
               FROM users ORDER BY id DESC"""
        ).fetchall()

    finally:
        conn.close()

    return render_template("users.html", users=users)


@app.route("/admin/users/<int:user_id>/delete", methods=["POST"])
@admin_required
def delete_user(user_id):
    conn = db()

    try:
        conn.execute(
            "DELETE FROM users WHERE id = %s AND role != 'admin'",
            (user_id,)
        )

        conn.commit()

    finally:
        conn.close()

    flash("User delete kar diya.", "success")
    return redirect(url_for("manage_users"))


@app.route("/admin/courses", methods=["GET", "POST"])
@admin_required
def manage_courses():
    if request.method == "POST":
        title = request.form["title"].strip()
        description = request.form["description"].strip()
        youtube_url = request.form["youtube_url"].strip()

        if not title:
            flash("Course title required hai.", "error")
            return redirect(url_for("manage_courses"))

        conn = db()

        try:
            conn.execute(
                """INSERT INTO courses
                   (title, description, youtube_url)
                   VALUES (%s, %s, %s)""",
                (title, description, youtube_url)
            )

            conn.commit()

        finally:
            conn.close()

        flash("Course add ho gaya.", "success")
        return redirect(url_for("manage_courses"))

    conn = db()

    try:
        courses = conn.execute(
            "SELECT * FROM courses ORDER BY id DESC"
        ).fetchall()

    finally:
        conn.close()

    return render_template("courses.html", courses=courses)


@app.route("/admin/courses/<int:course_id>/delete", methods=["POST"])
@admin_required
def delete_course(course_id):
    conn = db()

    try:
        conn.execute(
            "DELETE FROM courses WHERE id = %s",
            (course_id,)
        )

        conn.commit()

    finally:
        conn.close()

    flash("Course delete kar diya.", "success")
    return redirect(url_for("manage_courses"))


@app.route("/api/ask-ai", methods=["POST"])
@login_required
def ask_ai():
    data = request.get_json(silent=True) or {}
    question = data.get("question", "").strip()

    if not question:
        return jsonify({
            "ok": False,
            "error": "Question empty hai."
        }), 400

    api_key = os.environ.get("GROQ_API_KEY")

    if not api_key or Groq is None:
        return jsonify({
            "ok": False,
            "error": (
                "AI setup nahi hua. GROQ_API_KEY set karo "
                "aur requirements.txt mein groq rakho."
            )
        }), 503

    try:
        client = Groq(api_key=api_key)

        response = client.chat.completions.create(
            model=os.environ.get(
                "GROQ_MODEL",
                "openai/gpt-oss-20b"
            ),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are Ritik LearnHub AI Assistant. "
                        "Help students with Python, programming, "
                        "courses and study questions. "
                        "Explain concepts step-by-step in simple English. "
                        "Use examples and code when useful."
                    )
                },
                {
                    "role": "user",
                    "content": question
                }
            ],
            temperature=0.6,
            max_completion_tokens=2048
        )

        answer = response.choices[0].message.content

        return jsonify({
            "ok": True,
            "answer": answer
        })

    except Exception as exc:
        print("GROQ AI ERROR:", repr(exc))

        return jsonify({
            "ok": False,
            "error": (
                "AI response nahi aa saka. "
                "GROQ_API_KEY ya GROQ_MODEL check karo."
            )
        }), 500


# Initialize database tables when the app starts
init_db()


if __name__ == "__main__":
    app.run(debug=False)
