import os
import secrets
import string
import smtplib

import psycopg2
from psycopg2.extras import DictCursor
from dotenv import load_dotenv
from functools import wraps

from flask import (
    Flask, render_template, request, redirect,
    url_for, session, flash, jsonify
)

from werkzeug.security import (
    generate_password_hash, check_password_hash
)

load_dotenv()

try:
    from groq import Groq
except ImportError:
    Groq = None


app = Flask(__name__)
app.secret_key = os.environ.get(
    "FLASK_SECRET_KEY",
    "change-this-secret-key-in-production"
)


# ==============================
# DATABASE CONNECTION
# ==============================

class DBConnection:
    def __init__(self):
        database_url = os.environ.get("DATABASE_URL")

        if not database_url:
            raise RuntimeError(
                "DATABASE_URL Render Environment mein set karo."
            )

        self.conn = psycopg2.connect(
            database_url,
            cursor_factory=DictCursor
        )

    def cursor(self):
        return self.conn.cursor()

    def execute(self, query, params=None):
        cur = self.conn.cursor()
        cur.execute(query, params)
        return cur

    def executemany(self, query, params):
        cur = self.conn.cursor()
        cur.executemany(query, params)
        return cur

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def close(self):
        self.conn.close()


def db():
    return DBConnection()


# ==============================
# CREATE DATABASE TABLES
# ==============================

def init_db():
    conn = db()

    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'student',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS courses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                description TEXT,
                youtube_url TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        admin = conn.execute(
            "SELECT id FROM users WHERE username = %s",
            ("ritik",)
        ).fetchone()

        if not admin:
            admin_password = os.environ.get("ADMIN_PASSWORD")

            if not admin_password:
                raise RuntimeError(
                    "ADMIN_PASSWORD Render Environment mein set karo."
                )

            conn.execute(
                """
                INSERT INTO users
                (username, password_hash, role)
                VALUES (%s, %s, %s)
                """,
                (
                    "ritik",
                    generate_password_hash(admin_password),
                    "admin"
                )
            )

        count = conn.execute(
            "SELECT COUNT(*) FROM courses"
        ).fetchone()[0]

        if count == 0:
            conn.executemany(
                """
                INSERT INTO courses
                (title, description, youtube_url)
                VALUES (%s, %s, %s)
                """,
                [
                    (
                        "Python Basics",
                        "Variables, loops, functions aur beginner Python.",
                        "https://www.youtube.com/watch?v=rfscVS0vtbw"
                    ),
                    (
                        "Python OOP",
                        "Classes, objects aur OOP concepts.",
                        "https://www.youtube.com/watch?v=JeznW_7DlB0"
                    )
                ]
            )

        conn.commit()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


# ==============================
# LOGIN CHECKS
# ==============================

def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))

        return f(*args, **kwargs)

    return wrapper


def admin_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if session.get("role") != "admin":
            flash("Admin access required.", "error")
            return redirect(url_for("dashboard"))

        return f(*args, **kwargs)

    return wrapper


# ==============================
# PASSWORD GENERATOR
# ==============================

def make_password(length=10):
    alphabet = string.ascii_letters + string.digits + "!@#$"
    return "".join(
        secrets.choice(alphabet)
        for _ in range(length)
    )


# ==============================
# YOUTUBE EMBED
# ==============================

def youtube_embed(url):
    if not url:
        return ""

    if "youtu.be/" in url:
        video_id = url.split("youtu.be/")[-1].split("?")[0]

    elif "watch?v=" in url:
        video_id = url.split("watch?v=")[-1].split("&")[0]

    elif "youtube.com/embed/" in url:
        video_id = url.split("youtube.com/embed/")[-1].split("?")[0]

    else:
        return ""

    return f"https://www.youtube.com/embed/{video_id}"


@app.context_processor
def inject_helpers():
    return {"youtube_embed": youtube_embed}


# ==============================
# HOME PAGE
# ==============================

@app.route("/")
def index():
    if "user_id" in session:
        return redirect(url_for("dashboard"))

    return render_template("index.html")


# ==============================
# LOGIN
# ==============================

@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get(
            "username", ""
        ).strip().lower()

        password = request.form.get("password", "")

        conn = db()

        try:
            user = conn.execute(
                "SELECT * FROM users WHERE username = %s",
                (username,)
            ).fetchone()

        finally:
            conn.close()

        if user and check_password_hash(
            user["password_hash"], password
        ):
            session["user_id"] = user["id"]
            session["username"] = user["username"]
            session["role"] = user["role"]

            return redirect(url_for("dashboard"))

        flash("Username ya password galat hai.", "error")

    return render_template("login.html")


# ==============================
# CHANGE PASSWORD
# ==============================

@app.route("/login/pass", methods=["GET", "POST"])
def passe():
    if request.method == "POST":
        username = request.form.get(
            "username", ""
        ).strip().lower()

        oldpassword = request.form.get("old_password", "")
        newpass = request.form.get("new_password", "")
        conpass = request.form.get("confirm_password", "")

        conn = db()

        try:
            user = conn.execute(
                "SELECT * FROM users WHERE username = %s",
                (username,)
            ).fetchone()

            if not user:
                flash("Username galat hai.", "error")
                return redirect(url_for("passe"))

            if not check_password_hash(
                user["password_hash"], oldpassword
            ):
                flash("Purana password galat hai.", "error")
                return redirect(url_for("passe"))

            if not newpass:
                flash("Naya password khaali nahi ho sakta.", "error")
                return redirect(url_for("passe"))

            if newpass != conpass:
                flash(
                    "Password aur confirm password match nahi kar rahe.",
                    "error"
                )
                return redirect(url_for("passe"))

            conn.execute(
                """
                UPDATE users
                SET password_hash = %s
                WHERE id = %s
                """,
                (
                    generate_password_hash(newpass),
                    user["id"]
                )
            )

            conn.commit()

            session["user_id"] = user["id"]
            session["username"] = user["username"]
            session["role"] = user["role"]

        except Exception as exc:
            conn.rollback()
            print("CHANGE PASSWORD ERROR:", repr(exc))
            flash("Password change nahi ho saka.", "error")
            return redirect(url_for("passe"))

        finally:
            conn.close()

        return redirect(url_for("dashboard"))

    return render_template("passe.html")


# ==============================
# LOGOUT
# ==============================

@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


# ==============================
# DASHBOARD
# ==============================

@app.route("/dashboard")
@login_required
def dashboard():
    conn = db()

    try:
        courses = conn.execute(
            "SELECT * FROM courses ORDER BY id DESC"
        ).fetchall()

        users_count = conn.execute(
            "SELECT COUNT(*) FROM users"
        ).fetchone()[0]

    finally:
        conn.close()

    return render_template(
        "dashboard.html",
        courses=courses,
        users_count=users_count
    )


# ==============================
# ADD AND SHOW USERS
# EMAIL IS OPTIONAL
# ==============================

@app.route("/admin/users", methods=["GET", "POST"])
@admin_required
def manage_users():

    if request.method == "POST":

        # Email field missing or empty ho to bhi chalega
        username = request.form.get(
            "username", ""
        ).strip().lower()

        gmail = request.form.get(
            "gmail", ""
        ).strip()

        if not username:
            flash("Username required hai.", "error")
            return redirect(url_for("manage_users"))

        if " " in username:
            flash("Username mein space nahi hona chahiye.", "error")
            return redirect(url_for("manage_users"))

        # User ke liye temporary password
        temporary_password = make_password(10)

        conn = db()

        try:
            # Check username first
            existing_user = conn.execute(
                "SELECT id FROM users WHERE username = %s",
                (username,)
            ).fetchone()

            if existing_user:
                flash(
                    f"User '{username}' already exist karta hai.",
                    "error"
                )
                return redirect(url_for("manage_users"))

            # Create user
            conn.execute(
                """
                INSERT INTO users
                (username, password_hash, role)
                VALUES (%s, %s, %s)
                """,
                (
                    username,
                    generate_password_hash(temporary_password),
                    "student"
                )
            )

            # Save user in database
            conn.commit()

        except psycopg2.IntegrityError:
            conn.rollback()

            flash(
                f"Username '{username}' pehle se exist karta hai.",
                "error"
            )

            return redirect(url_for("manage_users"))

        except Exception as exc:
            conn.rollback()

            print("CREATE USER ERROR:", repr(exc))

            flash(
                "User create nahi ho saka. Render Logs check karo.",
                "error"
            )

            return redirect(url_for("manage_users"))

        finally:
            conn.close()

        # ==================================
        # EMAIL OPTIONAL
        # ==================================

        email_sent = False

        # Email khaali hai to email bhejne ki koshish bhi nahi hogi
        if gmail:

            try:
                sender = os.environ.get(
                    "GMAIL_SENDER", ""
                ).strip()

                app_password = os.environ.get(
                    "password_google", ""
                ).strip()

                # Gmail settings available hon tabhi send karo
                if sender and app_password:

                    message = f"""Subject: Ritik Learning Hub Login

Hello {username},

Your account has been created.

Username: {username}
Password: {temporary_password}

Please change your password after login.

Ritik Learning Hub
"""

                    with smtplib.SMTP(
                        "smtp.gmail.com",
                        587,
                        timeout=20
                    ) as server:

                        server.starttls()
                        server.login(sender, app_password)

                        server.sendmail(
                            sender,
                            gmail,
                            message
                        )

                    email_sent = True

                else:
                    print(
                        "Gmail settings missing. User created "
                        "without sending email."
                    )

            except Exception as exc:
                # Email error se saved user affect nahi hoga
                print("EMAIL ERROR:", repr(exc))

        # ==================================
        # SUCCESS MESSAGE
        # ==================================

        if not gmail:
            flash(
                f"User '{username}' create ho gaya. "
                f"Temporary password: {temporary_password}",
                "success"
            )

        elif email_sent:
            flash(
                f"User '{username}' create ho gaya aur "
                "password email par bhej diya gaya.",
                "success"
            )

        else:
            flash(
                f"User '{username}' create ho gaya, lekin email "
                f"nahi bheja ja saka. Temporary password: "
                f"{temporary_password}",
                "success"
            )

        return redirect(url_for("manage_users"))

    # ==================================
    # DISPLAY USERS
    # ==================================

    conn = db()

    try:
        users = conn.execute(
            """
            SELECT id, username, role, created_at
            FROM users
            ORDER BY id DESC
            """
        ).fetchall()

    except Exception as exc:
        print("LOAD USERS ERROR:", repr(exc))

        flash("Users load nahi ho paaye.", "error")
        users = []

    finally:
        conn.close()

    return render_template(
        "users.html",
        users=users
    )


# ==============================
# DELETE USER
# ==============================

@app.route(
    "/admin/users/<int:user_id>/delete",
    methods=["POST"]
)
@admin_required
def delete_user(user_id):
    conn = db()

    try:
        conn.execute(
            """
            DELETE FROM users
            WHERE id = %s AND role != 'admin'
            """,
            (user_id,)
        )

        conn.commit()

    except Exception as exc:
        conn.rollback()
        print("DELETE USER ERROR:", repr(exc))
        flash("User delete nahi ho saka.", "error")

    else:
        flash("User delete kar diya.", "success")

    finally:
        conn.close()

    return redirect(url_for("manage_users"))


# ==============================
# ADD AND SHOW COURSES
# ==============================

@app.route("/admin/courses", methods=["GET", "POST"])
@admin_required
def manage_courses():

    if request.method == "POST":

        title = request.form.get("title", "").strip()
        description = request.form.get(
            "description", ""
        ).strip()

        youtube_url = request.form.get(
            "youtube_url", ""
        ).strip()

        if not title:
            flash("Course title required hai.", "error")
            return redirect(url_for("manage_courses"))

        conn = db()

        try:
            conn.execute(
                """
                INSERT INTO courses
                (title, description, youtube_url)
                VALUES (%s, %s, %s)
                """,
                (title, description, youtube_url)
            )

            conn.commit()

        except Exception as exc:
            conn.rollback()
            print("ADD COURSE ERROR:", repr(exc))
            flash("Course add nahi ho saka.", "error")

        else:
            flash("Course add ho gaya.", "success")

        finally:
            conn.close()

        return redirect(url_for("manage_courses"))

    conn = db()

    try:
        courses = conn.execute(
            "SELECT * FROM courses ORDER BY id DESC"
        ).fetchall()

    finally:
        conn.close()

    return render_template(
        "courses.html",
        courses=courses
    )


# ==============================
# DELETE COURSE
# ==============================

@app.route(
    "/admin/courses/<int:course_id>/delete",
    methods=["POST"]
)
@admin_required
def delete_course(course_id):
    conn = db()

    try:
        conn.execute(
            "DELETE FROM courses WHERE id = %s",
            (course_id,)
        )

        conn.commit()

    except Exception as exc:
        conn.rollback()
        print("DELETE COURSE ERROR:", repr(exc))
        flash("Course delete nahi ho saka.", "error")

    else:
        flash("Course delete kar diya.", "success")

    finally:
        conn.close()

    return redirect(url_for("manage_courses"))


# ==============================
# AI ASSISTANT
# ==============================

@app.route("/api/ask-ai", methods=["POST"])
@login_required
def ask_ai():

    data = request.get_json(silent=True) or {}

    question = data.get("question", "").strip()

    if not question:
        return jsonify({
            "ok": False,
            "error": "Question empty hai."
        }), 400

    api_key = os.environ.get("GROQ_API_KEY")

    if not api_key or Groq is None:
        return jsonify({
            "ok": False,
            "error": (
                "AI setup nahi hua. GROQ_API_KEY set karo "
                "aur requirements.txt mein groq rakho."
            )
        }), 503

    try:
        client = Groq(api_key=api_key)

        response = client.chat.completions.create(
            model=os.environ.get(
                "GROQ_MODEL",
                "openai/gpt-oss-20b"
            ),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are Ritik Learning Hub AI Assistant. "
                        "Help students with Python, programming, "
                        "courses and study questions. Explain "
                        "concepts step-by-step in simple English. "
                        "Use examples and code when useful."
                    )
                },
                {
                    "role": "user",
                    "content": question
                }
            ],
            temperature=0.6,
            max_completion_tokens=2048
        )

        answer = response.choices[0].message.content

        return jsonify({
            "ok": True,
            "answer": answer
        })

    except Exception as exc:
        print("GROQ AI ERROR:", repr(exc))

        return jsonify({
            "ok": False,
            "error": (
                "AI response nahi aa saka. "
                "GROQ_API_KEY ya GROQ_MODEL check karo."
            )
        }), 500


# ==============================
# INITIALIZE DATABASE
# ==============================

init_db()


# ==============================
# RUN APP
# ==============================

if __name__ == "__main__":
    app.run(debug=False)
